{
 "title": "dash-payments-api",
 "description": "Saúde da payments-api",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  { "title": "API REST RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL REQUESTS/SEC",
   "type": "stat",
   "description": "Total requests per secs",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_gonic_request_duration_count{application=\"$application\", path=\"/payment\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " GENERAL ERROR 07",
   "type": "stat",
   "description": "Number of Transactions errors 07 in last minute",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_gonic_requests_total{application=\"$application\", path=\"/payment\", transactionCode=\"07\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "INSUFFICIENT FUNDS 51",
   "type": "stat",
   "description": "Number of Transactions errors 51 in last minute",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_gonic_requests_total{application=\"$application\", path=\"/payment\", transactionCode=\"51\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WIP: LATENCY AVERAGE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum(rate(gin_gonic_request_duration_bucket{application=\"$application\", path=\"/payment\"}[1m])) by (le)))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, (sum(rate(gin_gonic_request_duration_bucket{application=\"$application\", path=\"/payment\"}[1m])) by (le)))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, (sum(rate(gin_gonic_request_duration_bucket{application=\"$application\", path=\"/payment\"}[1m])) by (le)))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, (sum(rate(gin_gonic_request_duration_bucket{application=\"$application\", path=\"/payment\"}[1m])) by (le)))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, (sum(rate(gin_gonic_request_duration_bucket{application=\"$application\", path=\"/payment\"}[1m])) by (le)))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "ERROR (07, 51) RATE",
   "type": "timeseries",
   "description": "Error Rate in last 5 minutes",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(gin_gonic_requests_total{application=\"$application\", path=\"/payment\",  transactionCode=\"07\"}[5m])) / sum(rate(gin_gonic_requests_total{application=\"$application\", path=\"/payment\"}[5m]))",
     "legendFormat": "General Error 07"
    },
    {
     "expr": "sum(rate(gin_gonic_requests_total{application=\"$application\", path=\"/payment\",  transactionCode=\"51\"}[5m])) / sum(rate(gin_gonic_requests_total{application=\"$application\", path=\"/payment\"}[5m]))",
     "legendFormat": "Insufficient funds 51"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "description": "Means latency in last minute",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gin_gonic_request_duration_sum{application=\"$application\", path=\"/payment\"}[5m])",
     "legendFormat": "{{path}} {{method}} {{transactionCode}}"
    }
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "description": "Requests number per endoint in last minute",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(gin_gonic_request_duration_sum{application=\"$application\", path=\"/payment\"}[1m])) * 1000",
     "legendFormat": "/payment"
    }
   ]
  },
  {
   "title": "AVERAGE REQUEST DURATION",
   "type": "timeseries",
   "description": "AVERAGE REQUEST DURATION",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gin_gonic_request_duration_sum{application=\"$application\", path=\"/payment\"}[1m]) / rate(gin_gonic_request_duration_count{application=\"$application\", path=\"/payment\"}[1m])",
     "legendFormat": "{{path}} {{method}} {{transactionCode}}"
    }
   ]
  },
  {
   "title": "MAX REQUEST DURATION",
   "type": "timeseries",
   "description": "Maximun durantion of request",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gin_gonic_requests_total{application=\"$application\", transactionCode=\"00\", path=\"/payment\"}",
     "legendFormat": "{{path}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "API REST USE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "MEMORY ALLOC USE",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(memory_alloc_bytes{application=\"$application\"})*100 / sum(memory_total_alloc_bytes{application=\"$application\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU USAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"$application\"}",
       "legendFormat": "System CPU usage"
      },
      {
       "expr": "process_cpu_usage{application=\"$application\"}",
       "legendFormat": "Process CPU usage"
      }
     ]
    },
    {
     "title": "MEMORY AVERAGE USE",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(memory_used_bytes{application=\"$application\"}) / sum(memory_limit_bytes{application=\"$application\"})) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LOAD AVERAGE",
     "type": "timeseries",
     "description": "CPU usage mean",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 44 },
     "targets": [
      {
       "expr": "system_load_average_1m{application=\"$application\"}",
       "legendFormat": "Load average [1m]"
      },
      {
       "expr": "system_cpu_cores{application=\"$application\"}",
       "legendFormat": "CPU core size"
      }
     ]
    }
   ]
  },
  {
   "title": "API BASICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST START TIME",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"transaction-rest:8080\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "REST UPTIME",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PROCESSOR START TIME",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"pushgateway:9091\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WARN & ERROR LOG",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(log_events_total{application=\"$application\", level=\"info\"}[5m]))",
       "legendFormat": "Info"
      },
      {
       "expr": "sum(increase(log_events_total{application=\"$application\", level=\"warning\"}[5m]))",
       "legendFormat": "warning"
      },
      {
       "expr": "sum(increase(log_events_total{application=\"$application\", level=\"error\"}[5m]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "DB CONNECTION STATE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "gorm_dbstats_in_use{application=\"$application\"}",
       "legendFormat": "In Use"
      },
      {
       "expr": "gorm_dbstats_idle{application=\"$application\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "gorm_dbstats_wait_count{application=\"$application\"}",
       "legendFormat": "Pending"
      }
     ]
    }
   ]
  }
 ]
}